### ISSUE TITLE
Add a link to the whatsapp group

### ISSUE THREAD

**Issue by YonatanKra** [noam-honig/cfp-list#12]

**Comment by noam-honig** [comment]
@YonatanKra 
I don't know how to link to a WhatsApp group. 

If you meant a link to join the WhatsApp group, that link is only available for admins, so please prepare and send it to me.

**Comment by YonatanKra** [comment]
Here's the link: https://chat.whatsapp.com/ErE6atVxKqnAPb6rwiT22H
